src/rakuraku_apps/urls.py
from django.urls import path, include
from .views import log

from rakuraku_apps.views.common import (
    CustomLoginView,
    FunctionView,
    HomeView, 
    CustomLoginView,
    LogoutView,
    Omake1View,
    Omake2View,
    Omake3View,
    Omake4View,
    Omake5View,
    OmakeView, 
    SignupView
)
from rakuraku_apps.views.everyday_input import (
    EverydayCommentInputView, 
    EverydayConfirmInputView, 
    EverydayEditView, 
    EverydayFirstInputView, 
    EverydayOrIntervalView, 
    EverydaySecondInputView
)
from rakuraku_apps.views.interval_input import (
    IntervalCommentInputView, 
    IntervalConfirmInputView, 
    IntervalEditView, 
    IntervalFirstInputView, 
    IntervalSecondInputView, 
    IntervalThirdInputView
)
from rakuraku_apps.views.log import (
    GraphView, 
    TableOrGraphView, 
    TableView,
    export_to_excel
)
from rakuraku_apps.views.manage import (
    CreateShrimpView,
    CreateTankView,
    DeleteTankView,
    DeleteUserView,
    ManageValueView, 
    ManageTankView, 
    ManageUserView, 
    ManageView
)

app_name = "rakuraku_apps"

urlpatterns = [
    # ログイン画面
    path('', CustomLoginView.as_view(), name='login'),

    # ログアウト
    path('logout/', LogoutView.as_view(), name="logout"),

    # ユーザー新規登録画面
    path('signup/', SignupView.as_view(), name='signup'),

    # ホーム画面　機能選択
    path('home/', HomeView.as_view(), name='home'),

    # データ入力　日常測定・定期測定選択画面
    path('everyday_or_interval/', EverydayOrIntervalView.as_view(), name='everyday_or_interval'),

    # データ入力　日常入力１　日付・水槽・室温
    path('everyday/first_input/', EverydayFirstInputView.as_view(), name='everyday_first_input'),

    # データ入力　日常入力２　水温・pH・DO・塩分濃度
    path('everyday/second_input/', EverydaySecondInputView.as_view(), name='everyday_second_input'),

    # データ入力　日常入力３　備考
    path('everyday/comment/', EverydayCommentInputView.as_view(), name='everyday_comment'),

    # データ入力　日常入力４　確認画面
    path('everyday/confirm/', EverydayConfirmInputView.as_view(), name='everyday_confirm'),

    # データ入力　日常入力５　編集画面
    path('everyday/edit/', EverydayEditView.as_view(), name='everyday_edit'),

    # データ入力　定期測定１　日付・水槽・室温
    path('interval/first_input/', IntervalFirstInputView.as_view(), name='interval_first_input'),

    # データ入力　定期測定２　NH4・NO2・NO3
    path('interval/second_input/', IntervalSecondInputView.as_view(), name='interval_second_input'),

    # データ入力　定期測定３　Ca・Al・Mg
    path('interval/third_input/', IntervalThirdInputView.as_view(), name='interval_third_input'),

    # データ入力　定期測定４　備考
    path('interval/comment/', IntervalCommentInputView.as_view(), name='interval_comment'),

    # データ入力　定期測定５　確認画面
    path('interval/confirm/', IntervalConfirmInputView.as_view(), name='interval_confirm'),

    # データ入力　定期測定６　編集画面
    path('interval/edit/', IntervalEditView.as_view(), name='interval_edit'),

    # 過去のデータ　表・グラフ選択画面
    path('table_or_graph/', TableOrGraphView.as_view(), name='table_or_graph'),

    # 過去のデータ　表
    path('table/', TableView.as_view(), name='table'),

    # 過去のデータ　表　編集画面
    path('edit_water_quality/<int:pk>/', log.edit_water_quality, name='edit_water_quality'),

    # 過去のデータ　表　削除
    path('delete_water_quality/<int:pk>/', log.delete_water_quality, name='delete_water_quality'),

    # 過去のデータ　表　excel
    path('export_to_excel/', export_to_excel, name='export_to_excel'),

    # 過去のデータ　グラフ
    path('graph/', GraphView.as_view(), name='graph'),

    # 管理者画面　ホーム（ユーザー・水槽・水質基準値・警告範囲）
    path('manage/', ManageView.as_view(), name='manage'),

    # 管理者画面　ユーザー
    path('manage/user/', ManageUserView.as_view(), name='manage_user'),

    # 管理者画面　ユーザー削除
    path('manage/user/<int:pk>/delete/', DeleteUserView.as_view(), name='delete_user'),

    # 管理者画面　水槽
    path('manage/tank/', ManageTankView.as_view(), name='manage_tank'),

    # 管理者画面　水槽削除
    path('manage/tank/<int:pk>/delete/', DeleteTankView.as_view(), name='delete_tank'),

    # 管理者画面　水槽作成
    path('manage/create_tank', CreateTankView.as_view(), name='create_tank'),

    # 管理者画面　系統作成
    path('manage/create_shrimp', CreateShrimpView.as_view(), name='create_shrimp'),

    # 管理者画面　水質基準値
    path('manage/value/', ManageValueView.as_view(), name='manage_value'),

    # 機能紹介
    path('function', FunctionView.as_view(), name='function'),

    # おまけ
    path('ebimaster', OmakeView.as_view(), name='omake'),

    # おまけ1
    path('omikuji', Omake1View.as_view(), name='omake1'),

    # おまけ2
    path('shooting', Omake2View.as_view(), name='omake2'),

    # おまけ3
    path('puzzle', Omake3View.as_view(), name='omake3'),

    # おまけ4
    path('bbq', Omake4View.as_view(), name='omake4'),

    # おまけ5
    path('catching', Omake5View.as_view(), name='omake5'),
]

src/rakuraku_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rakuraku_apps.urls')),
]

src/rakuraku_apps/forms/common.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from rakuraku_apps.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "account_id",
        )

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        

src/rakuraku_apps/views/common.py
from django.urls import reverse_lazy

from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView as BaseLoginView, LogoutView as BaseLogoutView
from django.views.generic import CreateView
from django.contrib.auth import login, authenticate

from rakuraku_apps.forms.common import LoginForm, SignUpForm


class HomeView(TemplateView):
    template_name = 'home.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['success_message'] = self.request.session.pop('success_message', None)
        return context



class CustomLoginView(BaseLoginView):
    template_name = 'login.html'    
    form_class = LoginForm



class SignupView(CreateView):
    form_class = SignUpForm
    template_name = "signup.html" 
    success_url = reverse_lazy("rakuraku_apps:manage_user") # ユーザー作成後のリダイレクト先ページ
    

class LogoutView(BaseLogoutView):
    success_url = reverse_lazy("accounts:index")


class EverydayOrIntervalView(TemplateView):
    template_name = 'input/evryday_or_interval.html'

class FunctionView(TemplateView):
    template_name = 'function.html'

class OmakeView(TemplateView):
    template_name = 'omake.html'

class Omake1View(TemplateView):
    template_name = 'omake/omake1.html'

class Omake2View(TemplateView):
    template_name = 'omake/omake2.html'

class Omake3View(TemplateView):
    template_name = 'omake/omake3.html'

class Omake4View(TemplateView):
    template_name = 'omake/omake4.html'

class Omake5View(TemplateView):
    template_name = 'omake/omake5.html'

src/rakuraku_apps/views/everyday_input.py
import requests

from datetime import date, datetime, timedelta

from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.conf import settings

from rakuraku_apps.models import TankModel, WaterQualityModel, WaterQualityThresholdModel
from rakuraku_apps.forms.input import WaterQualityForm



class EverydayOrIntervalView(TemplateView):
    template_name = 'input/evryday_or_interval.html'
    def get(self, request, *args, **kwargs):
        request.session.pop('water_quality_id', None)
        request.session.pop('date', None)
        request.session.pop('tank', None)
        request.session.pop('room_temperature', None)
        request.session.pop('NH4', None)
        request.session.pop('NO2', None)
        request.session.pop('NO3', None)
        request.session.pop('Ca', None)
        request.session.pop('Al', None)
        request.session.pop('Mg', None)
        request.session.pop('notes', None)
        return super().get(request, *args, **kwargs)



class EverydayFirstInputView(TemplateView):
    template_name = 'input/everyday/first_input.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['tanks'] = TankModel.objects.all()
        today = date.today()
        context['today'] = today.strftime('%Y-%m-%d')

        # その日の日付のデータがすでに存在する場合は、そのデータを初期値として設定
        water_qualities = WaterQualityModel.objects.filter(date=today)
        if water_qualities.exists():
            context['initial_data'] = []
            for water_quality in water_qualities:
                context['initial_data'].append({
                    'tank': water_quality.tank.id,
                    'room_temperature': water_quality.room_temperature,
                    'water_temperature': water_quality.water_temperature,
                    'pH': water_quality.pH,
                    'DO': water_quality.DO,
                    'salinity': water_quality.salinity,
                    'notes': water_quality.notes,
                })

        return context

    def post(self, request, *args, **kwargs):
        date_str = request.POST['date']
        tank_id = request.POST['tank']
        room_temperature = request.POST['room_temperature']
        water_qualities = WaterQualityModel.objects.filter(date=date_str, tank_id=tank_id)
        if water_qualities.exists():
            water_quality = water_qualities.first()
            request.session['water_quality_id'] = water_quality.id
            
            request.session['date'] = water_quality.date.strftime('%Y-%m-%d')
            request.session['tank'] = water_quality.tank_id
            request.session['room_temperature'] = room_temperature
            
            request.session['water_temperature'] = water_quality.water_temperature or ''
            request.session['pH'] = water_quality.pH or ''
            request.session['DO'] = water_quality.DO or ''
            request.session['salinity'] = water_quality.salinity or ''
            
            request.session['notes'] = water_quality.notes or ''
        else:
            request.session['water_quality_id'] = None
            
            request.session['date'] = date_str
            request.session['tank'] = tank_id
            request.session['room_temperature'] = room_temperature
            
            request.session['water_temperature'] = ''
            request.session['pH'] = ''
            request.session['DO'] = ''
            request.session['salinity'] = ''
            
            request.session['notes'] = ''
        return redirect('/everyday/second_input/')



class EverydaySecondInputView(TemplateView):
    template_name = 'input/everyday/second_input.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_data'] = {
            'water_temperature': self.request.session.get('water_temperature', ''),
            'pH': self.request.session.get('pH', ''),
            'DO': self.request.session.get('DO', ''),
            'salinity': self.request.session.get('salinity', ''),
        }
        return context

    def post(self, request, *args, **kwargs):
        request.session['water_temperature'] = request.POST['water_temperature']
        request.session['pH'] = request.POST['pH']
        request.session['DO'] = request.POST['DO']
        request.session['salinity'] = request.POST['salinity']
        return redirect('/everyday/comment/')



class EverydayCommentInputView(TemplateView):
    template_name = 'input/everyday/comment_input.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_data'] = {
            'notes': self.request.session.get('notes', ''),
        }
        return context

    def post(self, request, *args, **kwargs):
        request.session['notes'] = request.POST['notes']
        return redirect('/everyday/confirm/')



class EverydayConfirmInputView(TemplateView):
    template_name = 'input/everyday/confirm.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tank_id = self.request.session.get('tank', '')
        tank = TankModel.objects.get(pk=tank_id)
        date = self.request.session.get('date', '')
        
        form_data = {
            'date': date,
            'tank': tank.name,
            'room_temperature': self.request.session.get('room_temperature', ''),
            'water_temperature': self.request.session.get('water_temperature', ''),
            'pH': self.request.session.get('pH', ''),
            'DO': self.request.session.get('DO', ''),
            'salinity': self.request.session.get('salinity', ''),
            'notes': self.request.session.get('notes', ''),
        }
        context['form_data'] = form_data
        
        # アラートメッセージと背景色を格納する辞書を初期化
        alerts = {}
        bg_colors = {}
        
        # 基準値の範囲内にあるかどうかを確認
        for param in ['water_temperature', 'pH', 'DO', 'salinity']:
            threshold = WaterQualityThresholdModel.objects.filter(parameter=param).first()
            if threshold:
                value = form_data.get(param)
                if value:
                    if threshold.reference_value_threshold_min and float(value) < threshold.reference_value_threshold_min:
                        diff = threshold.reference_value_threshold_min - float(value)
                        alerts.setdefault(param, []).append(f"基準値より{diff:.1f}↓")
                        bg_colors[param] = 'table-warning'
                    elif threshold.reference_value_threshold_max and float(value) > threshold.reference_value_threshold_max:
                        diff = float(value) - threshold.reference_value_threshold_max
                        alerts.setdefault(param, []).append(f"基準値より{diff:.1f}↑")
                        bg_colors[param] = 'table-warning'
        
        # 前日の値から大きく離れているかどうかを確認
        previous_day = datetime.strptime(date, '%Y-%m-%d').date() - timedelta(days=1)
        previous_water_quality = WaterQualityModel.objects.filter(date=previous_day, tank=tank).first()
        if previous_water_quality:
            for param in ['water_temperature', 'pH', 'DO', 'salinity']:
                threshold = WaterQualityThresholdModel.objects.filter(parameter=param).first()
                if threshold and threshold.previous_day_threshold:
                    current_value = form_data.get(param)
                    previous_value = getattr(previous_water_quality, param)
                    if current_value and previous_value:
                        diff = float(current_value) - previous_value
                        if abs(diff) > threshold.previous_day_threshold:
                            if diff > 0:
                                alerts.setdefault(param, []).append(f"前日より{diff:.1f}↑")
                            else:
                                alerts.setdefault(param, []).append(f"前日より{abs(diff):.1f}↓")
                            if param in bg_colors:
                                bg_colors[param] = 'table-danger'
                            else:
                                bg_colors[param] = 'table-warning'
        
        context['alerts'] = alerts
        context['bg_colors'] = bg_colors
        
        # 昨日、一昨日、一週間前の値を取得
        context['previous_values'] = {}
        for days in [1, 2]:
            previous_date = datetime.strptime(date, '%Y-%m-%d').date() - timedelta(days=days)
            previous_water_quality = WaterQualityModel.objects.filter(date=previous_date, tank=tank).first()
            if previous_water_quality:
                context['previous_values'][days] = {
                    'water_temperature': previous_water_quality.water_temperature,
                    'pH': previous_water_quality.pH,
                    'DO': previous_water_quality.DO,
                    'salinity': previous_water_quality.salinity,
                }
        
        # alertsをrequest.sessionに保存
        self.request.session['alerts'] = alerts
        context['notify_line'] = True

        return context

    def post(self, request, *args, **kwargs):
        form_data = {
            'date': request.session['date'],
            'tank': request.session['tank'],
            'room_temperature': request.session['room_temperature'],
            'water_temperature': request.session['water_temperature'],
            'pH': request.session['pH'],
            'DO': request.session['DO'],
            'salinity': request.session['salinity'],
            'notes': request.session['notes'],
            'notify_line': request.POST.get('notify_line', '') == 'on',
        }
        water_quality_id = request.session.get('water_quality_id')
        if water_quality_id:
            water_quality = WaterQualityModel.objects.get(id=water_quality_id)
            form = WaterQualityForm(form_data, instance=water_quality)
        else:

src/rakuraku_apps/templates/input/everyday/comment_input.html
{% extends 'base.html' %}
{% load static %}

{% block PageCss %}
<link href="{% static '/css/button.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}
<h1 class="card-title text-center mt-3" style="font-size: 32px; margin-bottom: 16px;">データ入力</h1> 
<h2 class="text-center mb-4">日常測定 Step3</h2>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<div class="container"> 
    <div class="row justify-content-center"> 
        <div class="col-md-6"> 
                <div class="card-body"> 
                    
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="notes" class="form-label">備考</label>
                            <textarea name="notes" class="form-control" rows="4">{{ form_data.notes }}</textarea>
                        </div>
                        <div class="d-grid gap-2">
                            <button type="submit" class="original-long-btn btn-space">次へ</button>
                            <a href="{% url 'rakuraku_apps:everyday_second_input' %}" class="original-long-btn-gray">戻る</a>
                        </div>
                    </form>
                </div>  
        </div> 
    </div> 
</div> 

{% else %} 
<div class="text-center mt-5"> 
    <p>データ入力機能を使用するにはログインが必要です。</p> 
    <a href="{% url 'rakuraku_apps:login' %}" class="btn btn-primary">ログイン</a> 
</div> 
{% endif %} 
{% endblock %}

src/rakuraku_apps/templates/input/everyday/confirm.html
{% extends 'base.html' %}
{% load static %}

{% block PageCss %}
<link href="{% static '/css/button.css' %}" rel="stylesheet">
{% endblock %}


{% block title %}
<h1 class="card-title text-center mt-3" style="font-size: 32px; margin-bottom: 16px;">データ入力</h1> 
<h2 class="text-center mb-4">日常測定 入力データの確認</h2>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card-body">
        <!-- <h2 class="card-title text-center mb-4">入力内容の確認</h2> -->
        <div class="d-inline-block text-start">
          <p>
            <strong>計測日:</strong>{{ form_data.date }}
          </p>
          <p>
            <strong>水槽:</strong>{{ form_data.tank }}
          </p>
          <p>
            <strong>室温:</strong>{{ form_data.room_temperature }} ℃
          </p>
          <table class="table">
            <thead>
              <tr>
                <th></th>
                <th class="text-nowrap text-center align-middle">今回</th>
                <th class="text-nowrap text-center align-middle">昨日</th>
                <th class="text-nowrap text-center align-middle">一昨日</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="align-middle"><strong>水温</strong></td>
                <td class="text-nowrap text-center align-middle {% if 'water_temperature' in bg_colors %}{{ bg_colors.water_temperature }}{% endif %}">
                  {{ form_data.water_temperature }}℃<br>
                  {% if 'water_temperature' in alerts %}
                    {% for message in alerts.water_temperature %}
                      <span class="text-danger small d-block">{{ message }}</span>
                    {% endfor %}
                  {% endif %}
                </td>
                <td class="text-nowrap text-center align-middle">{% if previous_values.1.water_temperature %}{{ previous_values.1.water_temperature }}℃{% endif %}</td>
                <td class="text-nowrap text-center align-middle">{% if previous_values.2.water_temperature %}{{ previous_values.2.water_temperature }}℃{% endif %}</td>
              </tr>
              <tr>
                <td class="align-middle"><strong>pH</strong></td>
                <td class="text-nowrap text-center align-middle {% if 'pH' in bg_colors %}{{ bg_colors.pH }}{% endif %}">
                  {{ form_data.pH }}<br>
                  {% if 'pH' in alerts %}
                    {% for message in alerts.pH %}
                      <span class="text-danger small d-block">{{ message }}</span>
                    {% endfor %}
                  {% endif %}
                </td>
                <td class="text-nowrap text-center align-middle">{% if previous_values.1.pH %}{{ previous_values.1.pH }}{% endif %}</td>
                <td class="text-nowrap text-center align-middle">{% if previous_values.2.pH %}{{ previous_values.2.pH }}{% endif %}</td>
              </tr>
              <tr>
                <td class="align-middle"><strong>DO</strong></td>
                <td class="text-nowrap text-center align-middle {% if 'DO' in bg_colors %}{{ bg_colors.DO }}{% endif %}">
                  {{ form_data.DO }}mg/L<br>
                  {% if 'DO' in alerts %}
                    {% for message in alerts.DO %}
                      <span class="text-danger small d-block">{{ message }}</span>
                    {% endfor %}
                  {% endif %}
                </td>
                <td class="text-nowrap text-center align-middle">{% if previous_values.1.DO %}{{ previous_values.1.DO }}mg/L{% endif %}</td>
                <td class="text-nowrap text-center align-middle">{% if previous_values.2.DO %}{{ previous_values.2.DO }}mg/L{% endif %}</td>
              </tr>
              <tr>
                <td class="align-middle"><strong>塩分濃度</strong></td>
                <td class="text-nowrap text-center align-middle {% if 'salinity' in bg_colors %}{{ bg_colors.salinity }}{% endif %}">
                  {{ form_data.salinity }}%<br>
                  {% if 'salinity' in alerts %}
                    {% for message in alerts.salinity %}
                      <span class="text-danger small d-block">{{ message }}</span>
                    {% endfor %}
                  {% endif %}
                </td>
                <td class="text-nowrap text-center align-middle">{% if previous_values.1.salinity %}{{ previous_values.1.salinity }}%{% endif %}</td>
                <td class="text-nowrap text-center align-middle">{% if previous_values.2.salinity %}{{ previous_values.2.salinity }}%{% endif %}</td>
              </tr>
            </tbody>
          </table>
          <p>
            <strong>備考:</strong>{{ form_data.notes }}
          </p>
        </div>
      </div>
      <form method="post" class="mt-4">
        {% csrf_token %}
        <div class="form-check mb-3 text-center">
          <div class="d-inline-block">
              <input class="form-check-input" type="checkbox" name="notify_line" id="notify_line" {% if notify_line %}checked{% endif %}>
              <label class="form-check-label" for="notify_line">
                  アラートをLINEに通知する
              </label>
            </div>
        </div>
        <div class="d-grid gap-2 btn-space">
            <button type="submit" class="original-long-btn btn-space">保存</button>
            <a href="{% url 'rakuraku_apps:everyday_edit' %}" class="original-long-btn-green btn-space">編集</a>
            <a href="{% url 'rakuraku_apps:everyday_comment' %}" class="original-long-btn-gray">戻る</a>
        </div>
    </form>
    </div>
  </div>
</div>
{% include 'footer.html' %}
{% else %}
<div class="text-center mt-5">
  <p>確認ページにアクセスするにはログインが必要です。</p>
  <a href="{% url 'rakuraku_apps:login' %}" class="btn btn-primary">ログイン</a>
</div>
{% endif %}
{% endblock %}

src/rakuraku_apps/templates/input/everyday/edit.html
{% extends 'base.html' %}
{% load static %}

{% block PageCss %}
<link href="{% static '/css/button.css' %}" rel="stylesheet">
<style>
    .form-label {
        font-weight: bold;
    }
    .form-control, .form-select {
        width: 100%;
        height: 60px;
        font-size: 18px;
    }
    textarea.form-control {
        height: 120px;
        resize: none;
    }
    .form-row {
        display: flex;
        justify-content: space-between;
        margin-bottom: 20px;
    }
    .form-row .form-group {
        width: 100%;
    }
    .form-row .form-group label {
        width: 120px;
    }
    .form-row .form-group input,
    .form-row .form-group select {
        width: calc(100% - 140px);
    }
    .form-row .form-group textarea {
        width: 100%;
    }
    @media (max-width: 576px) {
        .form-row .form-group label {
            width: 100%;
            margin-bottom: 5px;
        }
        .form-row .form-group input,
        .form-row .form-group select,
        .form-row .form-group textarea {
            width: 100%;
        }
    }
</style>
{% endblock %}

{% block title %}
<h1 class="card-title text-center mt-3" style="font-size: 32px; margin-bottom: 16px;">データ入力</h1> 
<h2 class="text-center mb-4">日常測定 入力データの編集</h2>
{% endblock %}

{% block content %}

{% if user.is_authenticated %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group">
                        <label for="{{ form.date.id_for_label }}" class="form-label">{{ form.date.label }}</label>
                        {{ form.date }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="{{ form.tank.id_for_label }}" class="form-label">{{ form.tank.label }}</label>
                        {{ form.tank }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="{{ form.room_temperature.id_for_label }}" class="form-label">{{ form.room_temperature.label }}</label>
                        {{ form.room_temperature }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="{{ form.water_temperature.id_for_label }}" class="form-label">{{ form.water_temperature.label }}</label>
                        {{ form.water_temperature }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="{{ form.pH.id_for_label }}" class="form-label">{{ form.pH.label }}</label>
                        {{ form.pH }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="{{ form.DO.id_for_label }}" class="form-label">{{ form.DO.label }}</label>
                        {{ form.DO }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="{{ form.salinity.id_for_label }}" class="form-label">{{ form.salinity.label }}</label>
                        {{ form.salinity }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="{{ form.notes.id_for_label }}" class="form-label">{{ form.notes.label }}</label>
                        {{ form.notes }}
                    </div>
                </div>
                <div class="d-grid gap-2 mt-4">
                    <button type="submit" class="original-long-btn btn-space">確認画面へ</button>
                    <a href="{% url 'rakuraku_apps:everyday_confirm' %}" class="original-long-btn-gray">戻る</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% include 'footer.html' %}

{% else %}
<div class="text-center mt-5">
    <p>編集ページにアクセスするにはログインが必要です。</p>
    <a href="{% url 'rakuraku_apps:login' %}" class="btn btn-primary">ログイン</a>
</div>
{% endif %}
{% endblock %}