src/rakuraku_apps/urls.py
from django.urls import path, include
from .views import log

from rakuraku_apps.views.common import (
    CustomLoginView,
    FunctionView,
    HomeView, 
    CustomLoginView,
    LogoutView,
    Omake1View,
    Omake2View,
    Omake3View,
    Omake4View,
    Omake5View,
    OmakeView, 
    SignupView
)
from rakuraku_apps.views.everyday_input import (
    EverydayCommentInputView, 
    EverydayConfirmInputView, 
    EverydayEditView, 
    EverydayFirstInputView, 
    EverydayOrIntervalView, 
    EverydaySecondInputView
)
from rakuraku_apps.views.interval_input import (
    IntervalCommentInputView, 
    IntervalConfirmInputView, 
    IntervalEditView, 
    IntervalFirstInputView, 
    IntervalSecondInputView, 
    IntervalThirdInputView
)
from rakuraku_apps.views.log import (
    GraphView, 
    TableOrGraphView, 
    TableView,
    export_to_excel
)
from rakuraku_apps.views.manage import (
    CreateShrimpView,
    CreateTankView,
    DeleteTankView,
    DeleteUserView,
    ManageValueView, 
    ManageTankView, 
    ManageUserView, 
    ManageView
)

app_name = "rakuraku_apps"

urlpatterns = [
    # ログイン画面
    path('', CustomLoginView.as_view(), name='login'),

    # ログアウト
    path('logout/', LogoutView.as_view(), name="logout"),

    # ユーザー新規登録画面
    path('signup/', SignupView.as_view(), name='signup'),

    # ホーム画面　機能選択
    path('home/', HomeView.as_view(), name='home'),

    # データ入力　日常測定・定期測定選択画面
    path('everyday_or_interval/', EverydayOrIntervalView.as_view(), name='everyday_or_interval'),

    # データ入力　日常入力１　日付・水槽・室温
    path('everyday/first_input/', EverydayFirstInputView.as_view(), name='everyday_first_input'),

    # データ入力　日常入力２　水温・pH・DO・塩分濃度
    path('everyday/second_input/', EverydaySecondInputView.as_view(), name='everyday_second_input'),

    # データ入力　日常入力３　備考
    path('everyday/comment/', EverydayCommentInputView.as_view(), name='everyday_comment'),

    # データ入力　日常入力４　確認画面
    path('everyday/confirm/', EverydayConfirmInputView.as_view(), name='everyday_confirm'),

    # データ入力　日常入力５　編集画面
    path('everyday/edit/', EverydayEditView.as_view(), name='everyday_edit'),

    # データ入力　定期測定１　日付・水槽・室温
    path('interval/first_input/', IntervalFirstInputView.as_view(), name='interval_first_input'),

    # データ入力　定期測定２　NH4・NO2・NO3
    path('interval/second_input/', IntervalSecondInputView.as_view(), name='interval_second_input'),

    # データ入力　定期測定３　Ca・Al・Mg
    path('interval/third_input/', IntervalThirdInputView.as_view(), name='interval_third_input'),

    # データ入力　定期測定４　備考
    path('interval/comment/', IntervalCommentInputView.as_view(), name='interval_comment'),

    # データ入力　定期測定５　確認画面
    path('interval/confirm/', IntervalConfirmInputView.as_view(), name='interval_confirm'),

    # データ入力　定期測定６　編集画面
    path('interval/edit/', IntervalEditView.as_view(), name='interval_edit'),

    # 過去のデータ　表・グラフ選択画面
    path('table_or_graph/', TableOrGraphView.as_view(), name='table_or_graph'),

    # 過去のデータ　表
    path('table/', TableView.as_view(), name='table'),

    # 過去のデータ　表　編集画面
    path('edit_water_quality/<int:pk>/', log.edit_water_quality, name='edit_water_quality'),

    # 過去のデータ　表　削除
    path('delete_water_quality/<int:pk>/', log.delete_water_quality, name='delete_water_quality'),

    # 過去のデータ　表　excel
    path('export_to_excel/', export_to_excel, name='export_to_excel'),

    # 過去のデータ　グラフ
    path('graph/', GraphView.as_view(), name='graph'),

    # 管理者画面　ホーム（ユーザー・水槽・水質基準値・警告範囲）
    path('manage/', ManageView.as_view(), name='manage'),

    # 管理者画面　ユーザー
    path('manage/user/', ManageUserView.as_view(), name='manage_user'),

    # 管理者画面　ユーザー削除
    path('manage/user/<int:pk>/delete/', DeleteUserView.as_view(), name='delete_user'),

    # 管理者画面　水槽
    path('manage/tank/', ManageTankView.as_view(), name='manage_tank'),

    # 管理者画面　水槽削除
    path('manage/tank/<int:pk>/delete/', DeleteTankView.as_view(), name='delete_tank'),

    # 管理者画面　水槽作成
    path('manage/create_tank', CreateTankView.as_view(), name='create_tank'),

    # 管理者画面　系統作成
    path('manage/create_shrimp', CreateShrimpView.as_view(), name='create_shrimp'),

    # 管理者画面　水質基準値
    path('manage/value/', ManageValueView.as_view(), name='manage_value'),

    # 機能紹介
    path('function', FunctionView.as_view(), name='function'),

    # おまけ
    path('ebimaster', OmakeView.as_view(), name='omake'),

    # おまけ1
    path('omikuji', Omake1View.as_view(), name='omake1'),

    # おまけ2
    path('shooting', Omake2View.as_view(), name='omake2'),

    # おまけ3
    path('puzzle', Omake3View.as_view(), name='omake3'),

    # おまけ4
    path('bbq', Omake4View.as_view(), name='omake4'),

    # おまけ5
    path('catching', Omake5View.as_view(), name='omake5'),
]

src/rakuraku_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rakuraku_apps.urls')),
]

src/rakuraku_apps/forms/common.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from rakuraku_apps.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "account_id",
        )

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        

src/rakuraku_apps/views/common.py
from django.urls import reverse_lazy

from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView as BaseLoginView, LogoutView as BaseLogoutView
from django.views.generic import CreateView
from django.contrib.auth import login, authenticate

from rakuraku_apps.forms.common import LoginForm, SignUpForm


class HomeView(TemplateView):
    template_name = 'home.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['success_message'] = self.request.session.pop('success_message', None)
        return context



class CustomLoginView(BaseLoginView):
    template_name = 'login.html'    
    form_class = LoginForm



class SignupView(CreateView):
    form_class = SignUpForm
    template_name = "signup.html" 
    success_url = reverse_lazy("rakuraku_apps:manage_user") # ユーザー作成後のリダイレクト先ページ
    

class LogoutView(BaseLogoutView):
    success_url = reverse_lazy("accounts:index")


class EverydayOrIntervalView(TemplateView):
    template_name = 'input/evryday_or_interval.html'

class FunctionView(TemplateView):
    template_name = 'function.html'

class OmakeView(TemplateView):
    template_name = 'omake.html'

class Omake1View(TemplateView):
    template_name = 'omake/omake1.html'

class Omake2View(TemplateView):
    template_name = 'omake/omake2.html'

class Omake3View(TemplateView):
    template_name = 'omake/omake3.html'

class Omake4View(TemplateView):
    template_name = 'omake/omake4.html'

class Omake5View(TemplateView):
    template_name = 'omake/omake5.html'

src/rakuraku_apps/views/everyday_input.py
import requests

from datetime import date, datetime, timedelta

from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.conf import settings

from rakuraku_apps.models import TankModel, WaterQualityModel, WaterQualityThresholdModel
from rakuraku_apps.forms.input import WaterQualityForm



class EverydayOrIntervalView(TemplateView):
    template_name = 'input/evryday_or_interval.html'
    def get(self, request, *args, **kwargs):
        request.session.pop('water_quality_id', None)
        request.session.pop('date', None)
        request.session.pop('tank', None)
        request.session.pop('room_temperature', None)
        request.session.pop('NH4', None)
        request.session.pop('NO2', None)
        request.session.pop('NO3', None)
        request.session.pop('Ca', None)
        request.session.pop('Al', None)
        request.session.pop('Mg', None)
        request.session.pop('notes', None)
        return super().get(request, *args, **kwargs)



class EverydayFirstInputView(TemplateView):
    template_name = 'input/everyday/first_input.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['tanks'] = TankModel.objects.all()
        today = date.today()
        context['today'] = today.strftime('%Y-%m-%d')

        # その日の日付のデータがすでに存在する場合は、そのデータを初期値として設定
        water_qualities = WaterQualityModel.objects.filter(date=today)
        if water_qualities.exists():
            context['initial_data'] = []
            for water_quality in water_qualities:
                context['initial_data'].append({
                    'tank': water_quality.tank.id,
                    'room_temperature': water_quality.room_temperature,
                    'water_temperature': water_quality.water_temperature,
                    'pH': water_quality.pH,
                    'DO': water_quality.DO,
                    'salinity': water_quality.salinity,
                    'notes': water_quality.notes,
                })

        return context

    def post(self, request, *args, **kwargs):
        date_str = request.POST['date']
        tank_id = request.POST['tank']
        room_temperature = request.POST['room_temperature']
        water_qualities = WaterQualityModel.objects.filter(date=date_str, tank_id=tank_id)
        if water_qualities.exists():
            water_quality = water_qualities.first()
            request.session['water_quality_id'] = water_quality.id
            
            request.session['date'] = water_quality.date.strftime('%Y-%m-%d')
            request.session['tank'] = water_quality.tank_id
            request.session['room_temperature'] = room_temperature
            
            request.session['water_temperature'] = water_quality.water_temperature or ''
            request.session['pH'] = water_quality.pH or ''
            request.session['DO'] = water_quality.DO or ''
            request.session['salinity'] = water_quality.salinity or ''
            
            request.session['notes'] = water_quality.notes or ''
        else:
            request.session['water_quality_id'] = None
            
            request.session['date'] = date_str
            request.session['tank'] = tank_id
            request.session['room_temperature'] = room_temperature
            
            request.session['water_temperature'] = ''
            request.session['pH'] = ''
            request.session['DO'] = ''
            request.session['salinity'] = ''
            
            request.session['notes'] = ''
        return redirect('/everyday/second_input/')



class EverydaySecondInputView(TemplateView):
    template_name = 'input/everyday/second_input.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_data'] = {
            'water_temperature': self.request.session.get('water_temperature', ''),
            'pH': self.request.session.get('pH', ''),
            'DO': self.request.session.get('DO', ''),
            'salinity': self.request.session.get('salinity', ''),
        }
        return context

    def post(self, request, *args, **kwargs):
        request.session['water_temperature'] = request.POST['water_temperature']
        request.session['pH'] = request.POST['pH']
        request.session['DO'] = request.POST['DO']
        request.session['salinity'] = request.POST['salinity']
        return redirect('/everyday/comment/')



class EverydayCommentInputView(TemplateView):
    template_name = 'input/everyday/comment_input.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_data'] = {
            'notes': self.request.session.get('notes', ''),
        }
        return context

    def post(self, request, *args, **kwargs):
        request.session['notes'] = request.POST['notes']
        return redirect('/everyday/confirm/')



class EverydayConfirmInputView(TemplateView):
    template_name = 'input/everyday/confirm.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tank_id = self.request.session.get('tank', '')
        tank = TankModel.objects.get(pk=tank_id)
        date = self.request.session.get('date', '')
        
        form_data = {
            'date': date,
            'tank': tank.name,
            'room_temperature': self.request.session.get('room_temperature', ''),
            'water_temperature': self.request.session.get('water_temperature', ''),
            'pH': self.request.session.get('pH', ''),
            'DO': self.request.session.get('DO', ''),
            'salinity': self.request.session.get('salinity', ''),
            'notes': self.request.session.get('notes', ''),
        }
        context['form_data'] = form_data
        
        # アラートメッセージと背景色を格納する辞書を初期化
        alerts = {}
        bg_colors = {}
        
        # 基準値の範囲内にあるかどうかを確認
        for param in ['water_temperature', 'pH', 'DO', 'salinity']:
            threshold = WaterQualityThresholdModel.objects.filter(parameter=param).first()
            if threshold:
                value = form_data.get(param)
                if value:
                    if threshold.reference_value_threshold_min and float(value) < threshold.reference_value_threshold_min:
                        diff = threshold.reference_value_threshold_min - float(value)
                        alerts.setdefault(param, []).append(f"基準値より{diff:.1f}↓")
                        bg_colors[param] = 'table-warning'
                    elif threshold.reference_value_threshold_max and float(value) > threshold.reference_value_threshold_max:
                        diff = float(value) - threshold.reference_value_threshold_max
                        alerts.setdefault(param, []).append(f"基準値より{diff:.1f}↑")
                        bg_colors[param] = 'table-warning'
        
        # 前日の値から大きく離れているかどうかを確認
        previous_day = datetime.strptime(date, '%Y-%m-%d').date() - timedelta(days=1)
        previous_water_quality = WaterQualityModel.objects.filter(date=previous_day, tank=tank).first()
        if previous_water_quality:
            for param in ['water_temperature', 'pH', 'DO', 'salinity']:
                threshold = WaterQualityThresholdModel.objects.filter(parameter=param).first()
                if threshold and threshold.previous_day_threshold:
                    current_value = form_data.get(param)
                    previous_value = getattr(previous_water_quality, param)
                    if current_value and previous_value:
                        diff = float(current_value) - previous_value
                        if abs(diff) > threshold.previous_day_threshold:
                            if diff > 0:
                                alerts.setdefault(param, []).append(f"前日より{diff:.1f}↑")
                            else:
                                alerts.setdefault(param, []).append(f"前日より{abs(diff):.1f}↓")
                            if param in bg_colors:
                                bg_colors[param] = 'table-danger'
                            else:
                                bg_colors[param] = 'table-warning'
        
        context['alerts'] = alerts
        context['bg_colors'] = bg_colors
        
        # 昨日、一昨日、一週間前の値を取得
        context['previous_values'] = {}
        for days in [1, 2]:
            previous_date = datetime.strptime(date, '%Y-%m-%d').date() - timedelta(days=days)
            previous_water_quality = WaterQualityModel.objects.filter(date=previous_date, tank=tank).first()
            if previous_water_quality:
                context['previous_values'][days] = {
                    'water_temperature': previous_water_quality.water_temperature,
                    'pH': previous_water_quality.pH,
                    'DO': previous_water_quality.DO,
                    'salinity': previous_water_quality.salinity,
                }
        
        # alertsをrequest.sessionに保存
        self.request.session['alerts'] = alerts
        context['notify_line'] = True

        return context

    def post(self, request, *args, **kwargs):
        form_data = {
            'date': request.session['date'],
            'tank': request.session['tank'],
            'room_temperature': request.session['room_temperature'],
            'water_temperature': request.session['water_temperature'],
            'pH': request.session['pH'],
            'DO': request.session['DO'],
            'salinity': request.session['salinity'],
            'notes': request.session['notes'],
            'notify_line': request.POST.get('notify_line', '') == 'on',
        }
        water_quality_id = request.session.get('water_quality_id')
        if water_quality_id:
            water_quality = WaterQualityModel.objects.get(id=water_quality_id)
            form = WaterQualityForm(form_data, instance=water_quality)
        else:

src/rakuraku_apps/templates/log/table.html
{% extends 'base.html' %}
{% load static %}

{% block PageCss %}
<link href="{% static '/css/button.css' %}" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<style>
    .btn-primary-muted {
        background-color: rgba(86, 178, 200, 0.8);
        border-color: rgba(86, 178, 200, 0.8);
    }
    .btn-primary-muted:hover {
        background-color: rgba(70, 145, 163, 0.8);
        border-color: rgba(70, 145, 163, 0.8);
    }
    .btn-danger-muted {
        background-color: rgba(200, 86, 86, 0.8);
        border-color: rgba(200, 86, 86, 0.8);
    }
    .btn-danger-muted:hover {
        background-color: rgba(163, 70, 70, 0.8);
        border-color: rgba(163, 70, 70, 0.8);
    }
</style>
{% endblock %}

{% load custom_tags %}

{% block title %}
<h1 class="card-title text-center mt-3" style="font-size: 32px; margin-bottom: 16px;">過去のデータ</h1>
<h2 class="text-center mb-4">水質データ（表）</h2>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<div class="container">
    <form method="GET" class="mb-4">
        <div class="row">
            <div class="col-md-4 mb-3">
                <div class="form-group">
                    <label for="date_range">期間</label>
                    <div class="input-group">
                        <input type="date" class="form-control" id="start_date" name="start_date" value="{{ start_date }}">
                        <div class="input-group-append input-group-prepend d-flex align-items-center">
                            <span class="mx-2">〜</span>
                        </div>
                        <input type="date" class="form-control" id="end_date" name="end_date" value="{{ end_date }}">
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <div class="form-group">
                    <label for="shrimp">系統</label>
                    <select class="form-control" id="shrimp" name="shrimp">
                        <option value="">全て</option>
                        {% for shrimp in shrimps %}
                        <option value="{{ shrimp.id }}" {% if shrimp.id|stringformat:"i" == request.GET.shrimp %}selected{% endif %}>{{ shrimp.family }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <div class="form-group">
                    <label for="item">項目</label>
                    <select class="form-control" id="item" name="item">
                        <option value="">全て</option>
                        <option value="water_temperature" {% if request.GET.item == "water_temperature" %}selected{% endif %}>水温</option>
                        <option value="pH" {% if request.GET.item == "pH" %}selected{% endif %}>pH</option>
                        <option value="DO" {% if request.GET.item == "DO" %}selected{% endif %}>DO</option>
                        <option value="salinity" {% if request.GET.item == "salinity" %}selected{% endif %}>塩分濃度</option>
                        <option value="NH4" {% if request.GET.item == "NH4" %}selected{% endif %}>NH4</option>
                        <option value="NO2" {% if request.GET.item == "NO2" %}selected{% endif %}>NO2</option>
                        <option value="NO3" {% if request.GET.item == "NO3" %}selected{% endif %}>NO3</option>
                        <option value="Ca" {% if request.GET.item == "Ca" %}selected{% endif %}>Ca</option>
                        <option value="Al" {% if request.GET.item == "Al" %}selected{% endif %}>Al</option>
                        <option value="Mg" {% if request.GET.item == "Mg" %}selected{% endif %}>Mg</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="d-grid gap-2">
            <button type="submit" class="original-long-btn btn-space">表示</button>
        </div>
        <div class="d-grid gap-2  my-3">
            <a href="{% url 'rakuraku_apps:export_to_excel' %}?start_date={{ start_date }}&end_date={{ end_date }}&shrimp={{ request.GET.shrimp }}&item={{ request.GET.item }}" class="original-long-btn-excel">
                <i class="fa-solid fa-download"></i>
                Excel出力
            </a>
        </div>
    </form>
    <hr>
    {% if request.GET.item %}
    <h3 class="text-start ps-3 mt-5 mb-4">
        {% if request.GET.item == "water_temperature" %}水温
        {% elif request.GET.item == "pH" %}pH
        {% elif request.GET.item == "DO" %}DO
        {% elif request.GET.item == "salinity" %}塩分濃度
        {% elif request.GET.item == "NH4" %}NH4
        {% elif request.GET.item == "NO2" %}NO2
        {% elif request.GET.item == "NO3" %}NO3
        {% elif request.GET.item == "Ca" %}Ca
        {% elif request.GET.item == "Al" %}Al
        {% elif request.GET.item == "Mg" %}Mg
        {% endif %}
    </h3>
    <div class="table-responsive mb-5">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th><nobr>測定日</nobr></th>
                    {% for tank in tanks %}
                    <th><nobr>{{ tank.name }}</nobr></th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for date, data_by_date in water_quality_data_by_date.items %}
                <tr>
                    <td><nobr>{{ date }}</nobr></td>
                    {% for tank in tanks %}
                    <td><nobr>{{ data_by_date|get_item:tank.name|default_if_none:"-" }}</nobr></td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    {% regroup water_quality_data by tank__name as tank_list %}
    {% for tank in tank_list %}
    <h3 class="text-start ps-3 mt-5">{{ tank.grouper }}</h3>
    <div class="table-responsive mb-5">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th><nobr>日付</nobr></th>
                    <th><nobr>室温</nobr></th>
                    <th><nobr>水温</nobr></th>
                    <th><nobr>pH</nobr></th>
                    <th><nobr>DO</nobr></th>
                    <th><nobr>塩分濃度</nobr></th>
                    <th><nobr>NH4</nobr></th>
                    <th><nobr>NO2</nobr></th>
                    <th><nobr>NO3</nobr></th>
                    <th><nobr>Ca</nobr></th>
                    <th><nobr>Al</nobr></th>
                    <th><nobr>Mg</nobr></th>
                    <th><nobr>備考</nobr></th>
                    <th><nobr>編集/削除</nobr></th>
                </tr>
            </thead>
            <tbody>
                {% for data in tank.list %}
                <tr>
                    <td><nobr>{{ data.date }}</nobr></td>
                    <td><nobr>{{ data.room_temperature|default:"-" }}</nobr></td>
                    <td><nobr>{{ data.water_temperature|default:"-" }}</nobr></td>
                    <td><nobr>{{ data.pH|default:"-" }}</nobr></td>
                    <td><nobr>{{ data.DO|default:"-" }}</nobr></td>
                    <td><nobr>{{ data.salinity|default:"-" }}</nobr></td>
                    <td><nobr>{{ data.NH4|default:"-" }}</nobr></td>
                    <td><nobr>{{ data.NO2|default:"-" }}</nobr></td>
                    <td><nobr>{{ data.NO3|default:"-" }}</nobr></td>
                    <td><nobr>{{ data.Ca|default:"-" }}</nobr></td>
                    <td><nobr>{{ data.Al|default:"-" }}</nobr></td>
                    <td><nobr>{{ data.Mg|default:"-" }}</nobr></td>
                    <td><nobr>{{ data.notes|default:"-" }}</nobr></td>
                    <td>
                        <a href="{% url 'rakuraku_apps:edit_water_quality' data.id %}" class="btn btn-sm btn-primary-muted">
                            <i class="fas fa-edit"></i>
                        </a>
                        <button type="button" class="btn btn-sm btn-danger-muted" data-bs-toggle="modal" data-bs-target="#deleteModal{{ data.id }}">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </td>
                </tr>
<!-- 削除確認モーダル -->
<div class="modal fade" id="deleteModal{{ data.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ data.id }}" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel{{ data.id }}">データの削除</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                本当にこのデータを削除しますか？
            </div>
            <div class="modal-footer">
                <form action="{% url 'rakuraku_apps:delete_water_quality' data.id %}" method="POST">
                    {% csrf_token %}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                    <button type="submit" class="btn btn-danger">削除</button>
                </form>
            </div>
        </div>
    </div>
</div>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endfor %}
    {% endif %}
</div>

<div class="d-grid gap-2">
    <a href="{% url 'rakuraku_apps:table_or_graph' %}" class="original-long-btn-gray btn-space">戻る</a>
</div>

{% include 'footer.html' %}
{% else %} 
    <div class="d-grid gap-2"> 
        <a href="{% url 'rakuraku_apps:login' %}" class="original-btn">ログイン</a> 
    </div> 
{% endif %} 
{% endblock %}

src/rakuraku_apps/templates/log/table_or_graph.html
{% extends 'base.html' %}
{% load static %}

{% block PageCss %}
<link href="{% static '/css/button.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

{% if user.is_authenticated %}

<div class="container"> 
    <h1 class="card-title text-center mt-3" style="font-size: 32px; margin-bottom: 16px;">過去のデータ</h1>
    <div class="row justify-content-center"> 
        <div class="col-md-6"> 
            <div class="card mt-5 border-0"> 
                <div class="card-body"> 
                    <div class="d-grid gap-3"> 
                        <a href="{% url 'rakuraku_apps:table' %}" class="original-big-btn"> 
                            <div class="d-flex align-items-center justify-content-center"> 
                                <i class="fas fa-table fa-lg me-3"></i> 
                                <span class="fs-5">表</span> 
                            </div> 
                        </a> 
                        <a href="{% url 'rakuraku_apps:graph' %}" class="original-big-btn"> 
                            <div class="d-flex align-items-center justify-content-center"> 
                                <i class="fas fa-chart-line fa-lg me-3"></i> 
                                <span class="fs-5">グラフ</span> 
                            </div> 
                        </a> 
                    </div> 
                </div> 
            </div> 
        </div> 
    </div>
</div> 

{% include 'footer.html' %} 

{% else %} 
<div class="text-center mt-5"> 
    <p>過去のデータを閲覧するにはログインが必要です。</p> 
    <a href="{% url 'rakuraku_apps:login' %}" class="original-long-btn">ログイン</a> 
</div> 
{% endif %} 
{% endblock %}